
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8s.yozel.co
  resources:
  - taints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.yozel.co
  resources:
  - taints/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.yozel.co
  resources:
  - taints/status
  verbs:
  - get
  - patch
  - update
