# permissions for end users to view taints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taint-viewer-role
rules:
- apiGroups:
  - k8s.yozel.co
  resources:
  - taints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.yozel.co
  resources:
  - taints/status
  verbs:
  - get
